package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// source is the canonical input the snapshot is derived from. Stored as
// JSON in source.json and re-read by tools or tests that want a
// machine-readable view without depending on the generated Go source.
type source struct {
	BCCCommit    string      `json:"bcc_commit"`
	KernelCommit string      `json:"kernel_commit"`
	Helpers      []helperRow `json:"helpers"`
	ProgramTypes []enumRow   `json:"program_types"`
	MapTypes     []enumRow   `json:"map_types"`
	GeneratedBy  string      `json:"generated_by"`
	Notes        string      `json:"notes,omitempty"`
}

type helperRow struct {
	UAPI    string        `json:"uapi"`    // e.g. "BPF_FUNC_bind"
	GoConst string        `json:"go"`      // e.g. "FnBind"
	Version kernelVersion `json:"version"` // major.minor introduced
}

type enumRow struct {
	UAPI    string        `json:"uapi"`    // e.g. "BPF_PROG_TYPE_KPROBE"
	GoConst string        `json:"go"`      // e.g. "Kprobe"
	Version kernelVersion `json:"version"`
}

func buildSource(bcc *bccTables, bccCommit, kernelCommit string) *source {
	src := &source{
		BCCCommit:    bccCommit,
		KernelCommit: kernelCommit,
		GeneratedBy:  "internal/kernelversions/cmd/kvgen",
		Notes:        "Generated. Do not edit by hand. Run `go generate ./internal/kernelversions/...`.",
	}

	// Helpers: UAPI key is "BPF_FUNC_bind", Go const is camelCase("Fn"+name).
	helperKeys := make([]string, 0, len(bcc.Helpers))
	for k := range bcc.Helpers {
		helperKeys = append(helperKeys, k)
	}
	sort.Strings(helperKeys)
	for _, name := range helperKeys {
		src.Helpers = append(src.Helpers, helperRow{
			UAPI:    "BPF_FUNC_" + name,
			GoConst: "Fn" + camelize(name),
			Version: bcc.Helpers[name],
		})
	}

	progKeys := make([]string, 0, len(bcc.ProgramTypes))
	for k := range bcc.ProgramTypes {
		progKeys = append(progKeys, k)
	}
	sort.Strings(progKeys)
	for _, k := range progKeys {
		src.ProgramTypes = append(src.ProgramTypes, enumRow{
			UAPI:    k,
			GoConst: ciliumProgTypeName(k),
			Version: bcc.ProgramTypes[k],
		})
	}

	mapKeys := make([]string, 0, len(bcc.MapTypes))
	for k := range bcc.MapTypes {
		mapKeys = append(mapKeys, k)
	}
	sort.Strings(mapKeys)
	for _, k := range mapKeys {
		src.MapTypes = append(src.MapTypes, enumRow{
			UAPI:    k,
			GoConst: ciliumMapTypeName(k),
			Version: bcc.MapTypes[k],
		})
	}

	return src
}

func writeSourceJSON(path string, src *source) error {
	buf, err := json.MarshalIndent(src, "", "  ")
	if err != nil {
		return err
	}
	buf = append(buf, '\n')
	return os.WriteFile(path, buf, 0o644)
}

func writeTablesGo(path string, src *source) error {
	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by internal/kernelversions/cmd/kvgen; DO NOT EDIT.")
	fmt.Fprintln(&b, "//")
	fmt.Fprintf(&b, "// BCC commit:    %s\n", src.BCCCommit)
	fmt.Fprintf(&b, "// Kernel commit: %s\n", src.KernelCommit)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package kernelversions")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"github.com/cilium/ebpf\"")
	fmt.Fprintln(&b, "\t\"github.com/cilium/ebpf/asm\"")
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "// HelperVersion maps each known eBPF helper to the kernel version that introduced it.")
	fmt.Fprintln(&b, "var HelperVersion = map[asm.BuiltinFunc]KernelVersion{")
	for _, h := range src.Helpers {
		// Skip helpers cilium/ebpf doesn't expose (the snapshot is the
		// intersection of BCC ⨯ cilium so unknown identifiers do not
		// produce uncompilable references).
		if !ciliumHasHelper(h.GoConst) {
			continue
		}
		fmt.Fprintf(&b, "\tasm.%s: {Major: %d, Minor: %d},\n", h.GoConst, h.Version.Major, h.Version.Minor)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "// ProgTypeVersion maps each known eBPF program type to the kernel version that introduced it.")
	fmt.Fprintln(&b, "var ProgTypeVersion = map[ebpf.ProgramType]KernelVersion{")
	for _, e := range src.ProgramTypes {
		if e.GoConst == "" || !ciliumHasProgType(e.GoConst) {
			continue
		}
		fmt.Fprintf(&b, "\tebpf.%s: {Major: %d, Minor: %d},\n", e.GoConst, e.Version.Major, e.Version.Minor)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "// MapTypeVersion maps each known eBPF map type to the kernel version that introduced it.")
	fmt.Fprintln(&b, "var MapTypeVersion = map[ebpf.MapType]KernelVersion{")
	for _, e := range src.MapTypes {
		if e.GoConst == "" || !ciliumHasMapType(e.GoConst) {
			continue
		}
		fmt.Fprintf(&b, "\tebpf.%s: {Major: %d, Minor: %d},\n", e.GoConst, e.Version.Major, e.Version.Minor)
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

// camelize turns "ktime_get_ns" into "KtimeGetNs".
func camelize(snake string) string {
	parts := strings.Split(snake, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
