// Code generated by go-enum DO NOT EDIT.
// Version: v0.6.0

// Built By: go install

package kfeatures

import (
	"fmt"
	"strings"
)

const (
	// FeatureBPFLSM is a Feature of type Bpf-Lsm.
	FeatureBPFLSM Feature = iota
	// FeatureBTF is a Feature of type Btf.
	FeatureBTF
	// FeatureIMA is a Feature of type Ima.
	FeatureIMA
	// FeatureKprobe is a Feature of type Kprobe.
	FeatureKprobe
	// FeatureKprobeMulti is a Feature of type Kprobe-Multi.
	FeatureKprobeMulti
	// FeatureFentry is a Feature of type Fentry.
	FeatureFentry
	// FeatureTracepoint is a Feature of type Tracepoint.
	FeatureTracepoint
	// FeatureCapBPF is a Feature of type Cap-Bpf.
	FeatureCapBPF
	// FeatureCapSysAdmin is a Feature of type Cap-Sys-Admin.
	FeatureCapSysAdmin
	// FeatureCapPerfmon is a Feature of type Cap-Perfmon.
	FeatureCapPerfmon
	// FeatureJITEnabled is a Feature of type Jit-Enabled.
	FeatureJITEnabled
	// FeatureJITHardened is a Feature of type Jit-Hardened.
	FeatureJITHardened
	// FeatureBPFSyscall is a Feature of type Bpf-Syscall.
	FeatureBPFSyscall
	// FeaturePerfEventOpen is a Feature of type Perf-Event-Open.
	FeaturePerfEventOpen
	// FeatureSleepableBPF is a Feature of type Sleepable-Bpf.
	FeatureSleepableBPF
	// FeatureTraceFS is a Feature of type Trace-Fs.
	FeatureTraceFS
	// FeatureBPFFS is a Feature of type Bpf-Fs.
	FeatureBPFFS
	// FeatureInitUserNS is a Feature of type Init-User-Ns.
	FeatureInitUserNS
	// FeatureUnprivilegedBPFDisabled is a Feature of type Unprivileged-Bpf-Disabled.
	FeatureUnprivilegedBPFDisabled
	// FeatureBPFStatsEnabled is a Feature of type Bpf-Stats-Enabled.
	FeatureBPFStatsEnabled
)

var ErrInvalidFeature = fmt.Errorf("not a valid Feature, try [%s]", strings.Join(_FeatureNames, ", "))

const _FeatureName = "bpf-lsmbtfimakprobekprobe-multifentrytracepointcap-bpfcap-sys-admincap-perfmonjit-enabledjit-hardenedbpf-syscallperf-event-opensleepable-bpftrace-fsbpf-fsinit-user-nsunprivileged-bpf-disabledbpf-stats-enabled"

var _FeatureNames = []string{
	_FeatureName[0:7],
	_FeatureName[7:10],
	_FeatureName[10:13],
	_FeatureName[13:19],
	_FeatureName[19:31],
	_FeatureName[31:37],
	_FeatureName[37:47],
	_FeatureName[47:54],
	_FeatureName[54:67],
	_FeatureName[67:78],
	_FeatureName[78:89],
	_FeatureName[89:101],
	_FeatureName[101:112],
	_FeatureName[112:127],
	_FeatureName[127:140],
	_FeatureName[140:148],
	_FeatureName[148:154],
	_FeatureName[154:166],
	_FeatureName[166:191],
	_FeatureName[191:208],
}

// FeatureNames returns a list of possible string values of Feature.
func FeatureNames() []string {
	tmp := make([]string, len(_FeatureNames))
	copy(tmp, _FeatureNames)
	return tmp
}

// FeatureValues returns a list of the values for Feature
func FeatureValues() []Feature {
	return []Feature{
		FeatureBPFLSM,
		FeatureBTF,
		FeatureIMA,
		FeatureKprobe,
		FeatureKprobeMulti,
		FeatureFentry,
		FeatureTracepoint,
		FeatureCapBPF,
		FeatureCapSysAdmin,
		FeatureCapPerfmon,
		FeatureJITEnabled,
		FeatureJITHardened,
		FeatureBPFSyscall,
		FeaturePerfEventOpen,
		FeatureSleepableBPF,
		FeatureTraceFS,
		FeatureBPFFS,
		FeatureInitUserNS,
		FeatureUnprivilegedBPFDisabled,
		FeatureBPFStatsEnabled,
	}
}

var _FeatureMap = map[Feature]string{
	FeatureBPFLSM:                  _FeatureName[0:7],
	FeatureBTF:                     _FeatureName[7:10],
	FeatureIMA:                     _FeatureName[10:13],
	FeatureKprobe:                  _FeatureName[13:19],
	FeatureKprobeMulti:             _FeatureName[19:31],
	FeatureFentry:                  _FeatureName[31:37],
	FeatureTracepoint:              _FeatureName[37:47],
	FeatureCapBPF:                  _FeatureName[47:54],
	FeatureCapSysAdmin:             _FeatureName[54:67],
	FeatureCapPerfmon:              _FeatureName[67:78],
	FeatureJITEnabled:              _FeatureName[78:89],
	FeatureJITHardened:             _FeatureName[89:101],
	FeatureBPFSyscall:              _FeatureName[101:112],
	FeaturePerfEventOpen:           _FeatureName[112:127],
	FeatureSleepableBPF:            _FeatureName[127:140],
	FeatureTraceFS:                 _FeatureName[140:148],
	FeatureBPFFS:                   _FeatureName[148:154],
	FeatureInitUserNS:              _FeatureName[154:166],
	FeatureUnprivilegedBPFDisabled: _FeatureName[166:191],
	FeatureBPFStatsEnabled:         _FeatureName[191:208],
}

// String implements the Stringer interface.
func (x Feature) String() string {
	if str, ok := _FeatureMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Feature(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Feature) IsValid() bool {
	_, ok := _FeatureMap[x]
	return ok
}

var _FeatureValue = map[string]Feature{
	_FeatureName[0:7]:     FeatureBPFLSM,
	_FeatureName[7:10]:    FeatureBTF,
	_FeatureName[10:13]:   FeatureIMA,
	_FeatureName[13:19]:   FeatureKprobe,
	_FeatureName[19:31]:   FeatureKprobeMulti,
	_FeatureName[31:37]:   FeatureFentry,
	_FeatureName[37:47]:   FeatureTracepoint,
	_FeatureName[47:54]:   FeatureCapBPF,
	_FeatureName[54:67]:   FeatureCapSysAdmin,
	_FeatureName[67:78]:   FeatureCapPerfmon,
	_FeatureName[78:89]:   FeatureJITEnabled,
	_FeatureName[89:101]:  FeatureJITHardened,
	_FeatureName[101:112]: FeatureBPFSyscall,
	_FeatureName[112:127]: FeaturePerfEventOpen,
	_FeatureName[127:140]: FeatureSleepableBPF,
	_FeatureName[140:148]: FeatureTraceFS,
	_FeatureName[148:154]: FeatureBPFFS,
	_FeatureName[154:166]: FeatureInitUserNS,
	_FeatureName[166:191]: FeatureUnprivilegedBPFDisabled,
	_FeatureName[191:208]: FeatureBPFStatsEnabled,
}

// ParseFeature attempts to convert a string to a Feature.
func ParseFeature(name string) (Feature, error) {
	if x, ok := _FeatureValue[name]; ok {
		return x, nil
	}
	return Feature(0), fmt.Errorf("%s is %w", name, ErrInvalidFeature)
}
